name: GitHub Issues Killer

on:
  # 定时触发
  schedule:
    # 每小时运行
    # - cron: '0 * * * *'
    - cron: '*/5 * * * *'
  
  # 允许手动触发
  workflow_dispatch:
    inputs:
      repos:
        description: '要监控的仓库 (格式: owner/repo1,owner/repo2)，留空监控全部'
        required: false
      keywords:
        description: '自定义关键词 (用逗号分隔)'
        required: false
        default: 'spam,恶意,虚假,suspicious,Star,star,异常增长'

jobs:
  scan-and-delete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: 运行Issues Killer脚本
        env:
          # 使用你在仓库中设置的secret
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # 区分手动和自动触发的配置
          # 自动触发时监控 JL-ghcoder/issues-killer
          REPOS_TO_MONITOR: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.repos || 'JL-ghcoder/issues-killer' }}
          # 关键词列表 - 手动触发时使用用户输入，自动触发时使用默认值
          SUSPICIOUS_KEYWORDS: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.keywords || 'spam,恶意,虚假,suspicious,Star,star,异常增长' }}
        run: python issues_killer_actions.py